// Validating benchmarks:
// ***** BenchmarkRunner: Start   *****
// ***** Found 3 benchmark(s) in total *****
// ***** Building 1 exe(s) in Parallel: Start   *****
BuildScript: E:\Sviluppo Software\OnlineRepos\UltraMapper.Suite\UltraMapper.Csv\UltraMapper.DataFileParsers.Benchmarks\bin\Release\net47\555da976-f1e8-4d9d-8a8d-cd405c9a3818.bat
// ***** Done, took 00:00:03 (3.77 sec)   *****
// Found 3 benchmarks:
//   SalesBenchmark.FileHelper: .NET 4.7(Runtime=.NET 4.7)
//   SalesBenchmark.CsvHelper: .NET 4.7(Runtime=.NET 4.7)
//   SalesBenchmark.UltraMapper: .NET 4.7(Runtime=.NET 4.7)

// **************************
// Benchmark: SalesBenchmark.FileHelper: .NET 4.7(Runtime=.NET 4.7)
// *** Execute ***
// Launch: 1 / 1
// Execute: E:\Sviluppo Software\OnlineRepos\UltraMapper.Suite\UltraMapper.Csv\UltraMapper.DataFileParsers.Benchmarks\bin\Release\net47\555da976-f1e8-4d9d-8a8d-cd405c9a3818.exe --benchmarkName "UltraMapper.Csv.Benchmarks.SalesBenchmark.FileHelper" --job ".NET 4.7" --benchmarkId 0 in 
// BeforeAnythingElse
Downloading test data... (170MB, will take a while)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sam\AppData\Local\Temp\UltraMapper.CSV.Benchmarks\Resources\5m Sales Records.zip'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at UltraMapper.Csv.Benchmarks.SalesBenchmark.DownloadSalesFile()
   at BenchmarkDotNet.Autogenerated.Runnable_0..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable_0.Run(IHost host, String benchmarkName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
ExitCode != 0
// Benchmark Process 20032 has exited with code -1
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: SalesBenchmark.CsvHelper: .NET 4.7(Runtime=.NET 4.7)
// *** Execute ***
// Launch: 1 / 1
// Execute: E:\Sviluppo Software\OnlineRepos\UltraMapper.Suite\UltraMapper.Csv\UltraMapper.DataFileParsers.Benchmarks\bin\Release\net47\555da976-f1e8-4d9d-8a8d-cd405c9a3818.exe --benchmarkName "UltraMapper.Csv.Benchmarks.SalesBenchmark.CsvHelper" --job ".NET 4.7" --benchmarkId 1 in 
// BeforeAnythingElse
Downloading test data... (170MB, will take a while)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sam\AppData\Local\Temp\UltraMapper.CSV.Benchmarks\Resources\5m Sales Records.zip'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at UltraMapper.Csv.Benchmarks.SalesBenchmark.DownloadSalesFile()
   at BenchmarkDotNet.Autogenerated.Runnable_1..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable_1.Run(IHost host, String benchmarkName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
ExitCode != 0
// Benchmark Process 21980 has exited with code -1
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// **************************
// Benchmark: SalesBenchmark.UltraMapper: .NET 4.7(Runtime=.NET 4.7)
// *** Execute ***
// Launch: 1 / 1
// Execute: E:\Sviluppo Software\OnlineRepos\UltraMapper.Suite\UltraMapper.Csv\UltraMapper.DataFileParsers.Benchmarks\bin\Release\net47\555da976-f1e8-4d9d-8a8d-cd405c9a3818.exe --benchmarkName "UltraMapper.Csv.Benchmarks.SalesBenchmark.UltraMapper" --job ".NET 4.7" --benchmarkId 2 in 
// BeforeAnythingElse
Downloading test data... (170MB, will take a while)

System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.Net.WebException: An exception occurred during a WebClient request. ---> System.IO.DirectoryNotFoundException: Could not find a part of the path 'C:\Users\Sam\AppData\Local\Temp\UltraMapper.CSV.Benchmarks\Resources\5m Sales Records.zip'.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access)
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   --- End of inner exception stack trace ---
   at System.Net.WebClient.DownloadFile(Uri address, String fileName)
   at UltraMapper.Csv.Benchmarks.SalesBenchmark.DownloadSalesFile()
   at BenchmarkDotNet.Autogenerated.Runnable_2..ctor()
   at BenchmarkDotNet.Autogenerated.Runnable_2.Run(IHost host, String benchmarkName)
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at BenchmarkDotNet.Autogenerated.UniqueProgramName.AfterAssemblyLoadingAttached(String[] args)
// AfterAll
ExitCode != 0
// Benchmark Process 23104 has exited with code -1
No more Benchmark runs will be launched as NO measurements were obtained from the previous run!


// ***** BenchmarkRunner: Finish  *****

// * Export *
  BenchmarkDotNet.Artifacts\results\UltraMapper.Csv.Benchmarks.SalesBenchmark-report.csv
  BenchmarkDotNet.Artifacts\results\UltraMapper.Csv.Benchmarks.SalesBenchmark-report-github.md
  BenchmarkDotNet.Artifacts\results\UltraMapper.Csv.Benchmarks.SalesBenchmark-report.html

// * Detailed results *
SalesBenchmark.FileHelper: .NET 4.7(Runtime=.NET 4.7)
Runtime = ; GC = 
There are not any results runs

SalesBenchmark.CsvHelper: .NET 4.7(Runtime=.NET 4.7)
Runtime = ; GC = 
There are not any results runs

SalesBenchmark.UltraMapper: .NET 4.7(Runtime=.NET 4.7)
Runtime = ; GC = 
There are not any results runs

// * Summary *

BenchmarkDotNet=v0.12.1, OS=Windows 10.0.19044
Intel Core i7-8700K CPU 3.70GHz (Coffee Lake), 1 CPU, 12 logical and 6 physical cores
  [Host] : .NET Framework 4.8 (4.8.4470.0), X64 RyuJIT  [AttachedDebugger]

Job=.NET 4.7  Runtime=.NET 4.7  

|      Method | Mean | Error |
|------------ |-----:|------:|
|  FileHelper |   NA |    NA |
|   CsvHelper |   NA |    NA |
| UltraMapper |   NA |    NA |

Benchmarks with issues:
  SalesBenchmark.FileHelper: .NET 4.7(Runtime=.NET 4.7)
  SalesBenchmark.CsvHelper: .NET 4.7(Runtime=.NET 4.7)
  SalesBenchmark.UltraMapper: .NET 4.7(Runtime=.NET 4.7)

// * Warnings *
Environment
  Summary -> Benchmark was executed with attached debugger
  Summary -> Detected error exit code from one of the benchmarks. It might be caused by following antivirus software:
        - Avira Antivirus (C:\Program Files (x86)\Avira\Antivirus\AviraSecurityCenterAgent.exe)
        - Windows Defender (windowsdefender://)
        - Avast Antivirus (C:\Program Files\AVAST Software\Avast\wsc_proxy.exe)
Use InProcessEmitToolchain or InProcessNoEmitToolchain to avoid new process creation.


// * Legends *
  Mean  : Arithmetic mean of all measurements
  Error : Half of 99.9% confidence interval
  1 ns  : 1 Nanosecond (0.000000001 sec)

// ***** BenchmarkRunner: End *****
// ** Remained 0 benchmark(s) to run **
Run time: 00:00:01 (1.92 sec), executed benchmarks: 3

Global total time: 00:00:05 (5.7 sec), executed benchmarks: 3
// * Artifacts cleanup *
